spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/movie
    username: postgres
    password: 123456
    driverClassName: org.postgresql.Driver

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

jpa:
  spring.jpa.database-platform: org.hibernate.dialect.PostgreSQL81Dialect
server:
  port: 8081
  error:
    include-message: ALWAYS