logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
server:
  error:
    include-message: always
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/store
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: create-drop
