spring:
  datasource:
    url: jdbc:h2:mem:crepet
    username: crepet
    password: crepet
    #driverClassName: org.h2.Driver
  jpa:
    #spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
  h2:
    console.enabled: true
    console.path: /db
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
