logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
server:
  error:
    include-message: always
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pizza
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
  session:
    store-type: jdbc
    timeout: 500
